// <auto-generated />
using System;
using Examen2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen2.Migrations
{
    [DbContext(typeof(ExamenContext))]
    partial class ExamenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen2.Database.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<Guid>("IdPrestamo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_autor");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroIdentidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("numero_Identidad");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPrestamo");

                    b.ToTable("cliente", "dbo");
                });

            modelBuilder.Entity("Examen2.Database.Entities.PrestamoEntity", b =>
                {
                    b.Property<Guid>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_prestamo");

                    b.Property<float>("Abono")
                        .HasColumnType("real")
                        .HasColumnName("abono");

                    b.Property<float>("Cuotas")
                        .HasColumnType("real")
                        .HasColumnName("cuotas");

                    b.Property<int>("DuracionPrestamo")
                        .HasColumnType("int")
                        .HasColumnName("duracion_prestamo");

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<float>("Interes")
                        .HasColumnType("real")
                        .HasColumnName("interes");

                    b.Property<float>("Saldo")
                        .HasColumnType("real")
                        .HasColumnName("capital_total");

                    b.HasKey("IdPrestamo");

                    b.ToTable("datos_prestamo", "dbo");
                });

            modelBuilder.Entity("Examen2.Database.Entities.ClienteEntity", b =>
                {
                    b.HasOne("Examen2.Database.Entities.PrestamoEntity", "Prestamo")
                        .WithMany()
                        .HasForeignKey("IdPrestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });
#pragma warning restore 612, 618
        }
    }
}
